In [139]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [120]:
DCLoan = pd.read_csv('state_DC.csv')
MDLoan = pd.read_csv('state_MD.csv')
VALoan = pd.read_csv('state_VA.csv')

C:\Users\marca\AppData\Local\Temp\ipykernel_19008\2040387108.py:2: DtypeWarning: Columns (0: loan_to_value_ratio, 1: interest_rate, 2: rate_spread, 3: total_loan_costs, 4: total_points_and_fees, 5: origination_charges, 6: discount_points, 7: lender_credits, 8: loan_term, 9: prepayment_penalty_term, 10: intro_rate_period, 11: property_value, 12: total_units, 13: multifamily_affordable_units) have mixed types. Specify dtype option on import or set low_memory=False.
  MDLoan = pd.read_csv('state_MD.csv')
C:\Users\marca\AppData\Local\Temp\ipykernel_19008\2040387108.py:3: DtypeWarning: Columns (0: loan_to_value_ratio, 1: interest_rate, 2: rate_spread, 3: total_loan_costs, 4: total_points_and_fees, 5: origination_charges, 6: discount_points, 7: lender_credits, 8: loan_term, 9: prepayment_penalty_term, 10: intro_rate_period, 11: property_value, 12: total_units, 13: multifamily_affordable_units) have mixed types. Specify dtype option on import or set low_memory=False.
  VALoan = pd.read_csv('state_VA.csv')

In [121]:
DMVLoan = pd.concat([DCLoan, MDLoan, VALoan], ignore_index=True)
print(DMVLoan.head())

   activity_year                   lei  derived_msa-md state_code  \
0           2023  549300VZVN841I2ILS84           47894         DC
1           2023  549300VZVN841I2ILS84           47894         DC
2           2023  549300VZVN841I2ILS84           47894         DC
3           2023  549300VZVN841I2ILS84           47894         DC
4           2023  549300VZVN841I2ILS84           47894         DC

   county_code  census_tract conforming_loan_limit derived_loan_product_type  \
0      11001.0  1.100100e+10                    NC   Conventional:First Lien
1      11001.0  1.100100e+10                     C   Conventional:First Lien
2      11001.0  1.100101e+10                     C   Conventional:First Lien
3      11001.0  1.100100e+10                     C   Conventional:First Lien
4      11001.0  1.100101e+10                     C   Conventional:First Lien

              derived_dwelling_category        derived_ethnicity  ...  \
0  Single Family (1-4 Units):Site-Built  Ethnicity Not Available  ...
1  Single Family (1-4 Units):Site-Built   Not Hispanic or Latino  ...
2  Single Family (1-4 Units):Site-Built   Not Hispanic or Latino  ...
3  Single Family (1-4 Units):Site-Built   Not Hispanic or Latino  ...
4  Single Family (1-4 Units):Site-Built  Ethnicity Not Available  ...

  denial_reason-2 denial_reason-3  denial_reason-4  tract_population  \
0             NaN             NaN              NaN              4072
1             NaN             NaN              NaN              4685
2             NaN             NaN              NaN              3215
3             NaN             NaN              NaN              3452
4             NaN             NaN              NaN              4590

   tract_minority_population_percent  ffiec_msa_md_median_family_income  \
0                              74.63                             150100
1                              71.50                             150100
2                              36.33                             150100
3                              39.77                             150100
4                              97.28                             150100

   tract_to_msa_income_percentage  tract_owner_occupied_units  \
0                          145.17                        1152
1                           60.29                         523
2                          125.55                        1057
3                          148.82                         500
4                           38.48                         706

   tract_one_to_four_family_homes  tract_median_age_of_housing_units
0                            1120                                  0
1                             214                                  0
2                             208                                 61
3                             164                                 62
4                            1301                                 56

[5 rows x 99 columns]

In [122]:
print(DMVLoan.head())

   activity_year                   lei  derived_msa-md state_code  \
0           2023  549300VZVN841I2ILS84           47894         DC
1           2023  549300VZVN841I2ILS84           47894         DC
2           2023  549300VZVN841I2ILS84           47894         DC
3           2023  549300VZVN841I2ILS84           47894         DC
4           2023  549300VZVN841I2ILS84           47894         DC

   county_code  census_tract conforming_loan_limit derived_loan_product_type  \
0      11001.0  1.100100e+10                    NC   Conventional:First Lien
1      11001.0  1.100100e+10                     C   Conventional:First Lien
2      11001.0  1.100101e+10                     C   Conventional:First Lien
3      11001.0  1.100100e+10                     C   Conventional:First Lien
4      11001.0  1.100101e+10                     C   Conventional:First Lien

              derived_dwelling_category        derived_ethnicity  ...  \
0  Single Family (1-4 Units):Site-Built  Ethnicity Not Available  ...
1  Single Family (1-4 Units):Site-Built   Not Hispanic or Latino  ...
2  Single Family (1-4 Units):Site-Built   Not Hispanic or Latino  ...
3  Single Family (1-4 Units):Site-Built   Not Hispanic or Latino  ...
4  Single Family (1-4 Units):Site-Built  Ethnicity Not Available  ...

  denial_reason-2 denial_reason-3  denial_reason-4  tract_population  \
0             NaN             NaN              NaN              4072
1             NaN             NaN              NaN              4685
2             NaN             NaN              NaN              3215
3             NaN             NaN              NaN              3452
4             NaN             NaN              NaN              4590

   tract_minority_population_percent  ffiec_msa_md_median_family_income  \
0                              74.63                             150100
1                              71.50                             150100
2                              36.33                             150100
3                              39.77                             150100
4                              97.28                             150100

   tract_to_msa_income_percentage  tract_owner_occupied_units  \
0                          145.17                        1152
1                           60.29                         523
2                          125.55                        1057
3                          148.82                         500
4                           38.48                         706

   tract_one_to_four_family_homes  tract_median_age_of_housing_units
0                            1120                                  0
1                             214                                  0
2                             208                                 61
3                             164                                 62
4                            1301                                 56

[5 rows x 99 columns]

In [123]:
DMVLoan.isnull().sum()[DMVLoan.isnull().sum() > 0]

county_code                       3995
census_tract                      4821
conforming_loan_limit             1272
loan_to_value_ratio             188122
interest_rate                   188859
rate_spread                     276383
total_loan_costs                270575
total_points_and_fees           529409
origination_charges             269425
discount_points                 374243
lender_credits                  449748
loan_term                         5405
prepayment_penalty_term         516894
intro_rate_period               417648
property_value                  113775
multifamily_affordable_units    530219
income                           73210
debt_to_income_ratio            183115
applicant_ethnicity-1              255
applicant_ethnicity-2           525588
applicant_ethnicity-3           541720
applicant_ethnicity-4           542082
applicant_ethnicity-5           542089
co-applicant_ethnicity-1            69
co-applicant_ethnicity-2        536461
co-applicant_ethnicity-3        541995
co-applicant_ethnicity-4        542096
co-applicant_ethnicity-5        542096
applicant_race-1                   172
applicant_race-2                514202
applicant_race-3                539653
applicant_race-4                541786
applicant_race-5                542010
co-applicant_race-1                 41
co-applicant_race-2             531765
co-applicant_race-3             541338
co-applicant_race-4             542015
co-applicant_race-5             542071
applicant_age_above_62           71508
co-applicant_age_above_62       362654
aus-2                           519001
aus-3                           534490
aus-4                           537822
aus-5                           538269
denial_reason-2                 520962
denial_reason-3                 538850
denial_reason-4                 541749
dtype: int64

In [124]:
print(DMVLoan.columns.tolist())

['activity_year', 'lei', 'derived_msa-md', 'state_code', 'county_code', 'census_tract', 'conforming_loan_limit', 'derived_loan_product_type', 'derived_dwelling_category', 'derived_ethnicity', 'derived_race', 'derived_sex', 'action_taken', 'purchaser_type', 'preapproval', 'loan_type', 'loan_purpose', 'lien_status', 'reverse_mortgage', 'open-end_line_of_credit', 'business_or_commercial_purpose', 'loan_amount', 'loan_to_value_ratio', 'interest_rate', 'rate_spread', 'hoepa_status', 'total_loan_costs', 'total_points_and_fees', 'origination_charges', 'discount_points', 'lender_credits', 'loan_term', 'prepayment_penalty_term', 'intro_rate_period', 'negative_amortization', 'interest_only_payment', 'balloon_payment', 'other_nonamortizing_features', 'property_value', 'construction_method', 'occupancy_type', 'manufactured_home_secured_property_type', 'manufactured_home_land_property_interest', 'total_units', 'multifamily_affordable_units', 'income', 'debt_to_income_ratio', 'applicant_credit_score_type', 'co-applicant_credit_score_type', 'applicant_ethnicity-1', 'applicant_ethnicity-2', 'applicant_ethnicity-3', 'applicant_ethnicity-4', 'applicant_ethnicity-5', 'co-applicant_ethnicity-1', 'co-applicant_ethnicity-2', 'co-applicant_ethnicity-3', 'co-applicant_ethnicity-4', 'co-applicant_ethnicity-5', 'applicant_ethnicity_observed', 'co-applicant_ethnicity_observed', 'applicant_race-1', 'applicant_race-2', 'applicant_race-3', 'applicant_race-4', 'applicant_race-5', 'co-applicant_race-1', 'co-applicant_race-2', 'co-applicant_race-3', 'co-applicant_race-4', 'co-applicant_race-5', 'applicant_race_observed', 'co-applicant_race_observed', 'applicant_sex', 'co-applicant_sex', 'applicant_sex_observed', 'co-applicant_sex_observed', 'applicant_age', 'co-applicant_age', 'applicant_age_above_62', 'co-applicant_age_above_62', 'submission_of_application', 'initially_payable_to_institution', 'aus-1', 'aus-2', 'aus-3', 'aus-4', 'aus-5', 'denial_reason-1', 'denial_reason-2', 'denial_reason-3', 'denial_reason-4', 'tract_population', 'tract_minority_population_percent', 'ffiec_msa_md_median_family_income', 'tract_to_msa_income_percentage', 'tract_owner_occupied_units', 'tract_one_to_four_family_homes', 'tract_median_age_of_housing_units']

In [125]:
ColumnsToKeep = [
	"interest_rate",
	"loan_to_value_ratio",
	"debt_to_income_ratio",
	"property_value",
	"income",
	"applicant_sex",
	"state_code",
	"applicant_credit_score_type",
	"submission_of_application",
    "derived_race",
    "loan_type",
    "action_taken",
    "loan_purpose",
    "loan_term",
    "loan_amount",
    "county_code",
]

DMVLoan[ColumnsToKeep].head()

,interest_rate,loan_to_value_ratio,debt_to_income_ratio,property_value,income,applicant_sex,state_code,applicant_credit_score_type,submission_of_application,derived_race,loan_type,action_taken,loan_purpose,loan_term,loan_amount,county_code
0,6.500,54.34800,40,2305000,332.0,1,DC,1,1,Race Not Available,1,1,1,360,1255000.0,11001.0
1,6.950,95.00000,36,275000,95.0,1,DC,3,1,White,1,1,1,360,265000.0,11001.0
2,6.625,80.00000,41,255000,70.0,1,DC,3,1,White,1,1,1,360,205000.0,11001.0
3,6.490,68.00000,37,625000,116.0,1,DC,2,1,White,1,1,1,360,425000.0,11001.0
4,NaN,NaN,NaN,NaN,NaN,3,DC,9,1,Race Not Available,1,4,1,360,205000.0,11001.0

In [126]:
print(DMVLoan[ColumnsToKeep].shape)
print(DMVLoan[ColumnsToKeep].isnull().sum())

(542099, 16)
interest_rate                  188859
loan_to_value_ratio            188122
debt_to_income_ratio           183115
property_value                 113775
income                          73210
applicant_sex                       0
state_code                          0
applicant_credit_score_type         0
submission_of_application           0
derived_race                        0
loan_type                           0
action_taken                        0
loan_purpose                        0
loan_term                        5405
loan_amount                         0
county_code                      3995
dtype: int64

In [127]:
DMVLoan = DMVLoan[ColumnsToKeep].dropna(subset=["loan_term", "county_code"])

print(DMVLoan.shape)

(532726, 16)

In [128]:
DMVHLoan = DMVLoan[DMVLoan["loan_purpose"] == 1]
print(DMVHLoan.shape)

(297146, 16)

In [129]:
DMVHLoan.value_counts("action_taken")

action_taken
1    166385
6     57209
4     38794
3     22060
5      7193
2      4868
8       427
7       210
Name: count, dtype: int64

1 = Loan originated (approved and closed)
3 = Application denied
4 = Application withdrawn
6 = Purchased loan

In [130]:
DMVHLoan.value_counts("derived_race")

derived_race
White                                        124677
Race Not Available                            95766
Black or African American                     45265
Asian                                         21355
Joint                                          7622
American Indian or Alaska Native               1023
2 or more minority races                       1005
Native Hawaiian or Other Pacific Islander       388
Free Form Text Only                              45
Name: count, dtype: int64

In [131]:
DMVHLoan.value_counts("applicant_sex")

applicant_sex
1    135657
2     89837
4     55201
3     16357
6        94
Name: count, dtype: int64

1 - Male
2 - Female
3 - Information not provided by applicant in mail, internet, or telephone application
4 - Not applicable
5 - No co-applicant
6 - Co-applicant selected both male and female

In [132]:
DMVHLoan["action_taken_label"] = DMVHLoan["action_taken"].replace({
	1: "Approved",
    2: "Approved but not accepted",
	3: "Denied",
	4: "Withdrawn",
    5: "file closed for incompleteness",
	6: "Loan Purchased",
    7: "Preapproval Denied",
    8: "Preapproval approved but no accepted"
})

DMVHLoan["applicant_sex_label"] = DMVHLoan["applicant_sex"].replace({
	1: "Male",
	2: "Female",
    3: "Information Not Provided",
    4: "Not Applicable",
    6: "Applicant selected both male and female"
})

DMVHLoan[["action_taken_label", "applicant_sex_label"]].head()

  action_taken_label       applicant_sex_label
0           Approved                      Male
1           Approved                      Male
2           Approved                      Male
3           Approved                      Male
4          Withdrawn  Information Not Provided

In [133]:
DMVHLoan["action_taken_label"].value_counts(normalize=True)

action_taken_label
Approved                                0.559944
Loan Purchased                          0.192528
Withdrawn                               0.130555
Denied                                  0.074240
file closed for incompleteness          0.024207
Approved but not accepted               0.016383
Preapproval approved but no accepted    0.001437
Preapproval Denied                      0.000707
Name: proportion, dtype: float64

In [134]:
ApprovalRate = DMVHLoan[DMVHLoan["action_taken_label"].isin(["Approved", "Denied"])]

In [135]:
ApprovalByRace = (
    ApprovalRate
    .groupby(["derived_race", "action_taken_label"])
    .size()
    .reset_index(name="count")
    .assign(
        proportion=lambda df: df.groupby("derived_race")["count"].transform(lambda s: s / s.sum())
    )
    [["derived_race", "action_taken_label", "proportion"]]
)

print(ApprovalByRace)

                                 derived_race action_taken_label  proportion
0                    2 or more minority races           Approved    0.817927
1                    2 or more minority races             Denied    0.182073
2            American Indian or Alaska Native           Approved    0.792428
3            American Indian or Alaska Native             Denied    0.207572
4                                       Asian           Approved    0.891180
5                                       Asian             Denied    0.108820
6                   Black or African American           Approved    0.813607
7                   Black or African American             Denied    0.186393
8                         Free Form Text Only           Approved    0.567568
9                         Free Form Text Only             Denied    0.432432
10                                      Joint           Approved    0.916340
11                                      Joint             Denied    0.083660
12  Native Hawaiian or Other Pacific Islander           Approved    0.806452
13  Native Hawaiian or Other Pacific Islander             Denied    0.193548
14                         Race Not Available           Approved    0.873371
15                         Race Not Available             Denied    0.126629
16                                      White           Approved    0.907849
17                                      White             Denied    0.092151

In [136]:
ApprovalByRace.to_csv("ApprovalByRace.csv", index=False)

In [137]:
ApprovalBySex = (
    ApprovalRate
    .groupby(["applicant_sex_label", "action_taken_label"])
    .size()
    .reset_index(name="count")
    .assign(
        proportion=lambda df: df.groupby("applicant_sex_label")["count"].transform(lambda s: s / s.sum())
    )
    [["applicant_sex_label", "action_taken_label", "proportion"]]
)

print(ApprovalBySex)

                       applicant_sex_label action_taken_label  proportion
0  Applicant selected both male and female           Approved    0.800000
1  Applicant selected both male and female             Denied    0.200000
2                                   Female           Approved    0.871926
3                                   Female             Denied    0.128074
4                 Information Not Provided           Approved    0.873521
5                 Information Not Provided             Denied    0.126479
6                                     Male           Approved    0.891446
7                                     Male             Denied    0.108554
8                           Not Applicable           Approved    0.879549
9                           Not Applicable             Denied    0.120451

In [138]:
ApprovalBySex.to_csv("ApprovalBySex.csv", index=False)

In [151]:
LoanAmountByRace = (
    DMVHLoan
    .groupby("derived_race")["loan_amount"]
    .mean()
    .reset_index(name="loan_amount")
)
LoanAmountByRace = round(LoanAmountByRace, 2)

print(LoanAmountByRace)

                                derived_race  loan_amount
0                   2 or more minority races    362054.73
1           American Indian or Alaska Native    316427.17
2                                      Asian    492245.14
3                  Black or African American    356168.45
4                        Free Form Text Only    369000.00
5                                      Joint    497021.78
6  Native Hawaiian or Other Pacific Islander    348608.25
7                         Race Not Available    435162.17
8                                      White    375820.44

In [ ]:
ApprovalRateByState = (
    ApprovalRate
    .assign(approved=lambda df: df["action_taken_label"] == "Approved")
    .groupby("state_code")["approved"]
    .mean()
    .reset_index(name="approval_rate")
)

print(ApprovalRateByState)

print(ApprovalRateByState)

TypeError: Cannot use numeric_only=True with SeriesGroupBy.mean and non-numeric dtypes.